name: Scheduled News Update

on:
  schedule:
    # Runs at 22 and 44 minutes past every hour
    - cron: '22,44 * * * *'
  workflow_dispatch: # Keeps the "Run workflow" button active

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install httpx beautifulsoup4

      - name: Run Scraper
        run: python fetch_news.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add news_data.json
          git commit -m "Automated News Update" || exit 0
          git push
